
#hey travis, I need sudo
sudo: required

#hey travis, I need docker
services:
  - docker

#hey travis, do this before trying to run scripts
before_install:
  - docker build -t wildncrazyguy/react-test -f client/Dockerfile.dev ./client

#scripts are run until we are done or hit an error
#travis expects the running command to exit (so cant just run npm run test)
script:
  - docker run wildncrazyguy/react-test npm run test -- --coverage

after_success:
  - docker build -t wildncrazyguy/multi-client -f client/Dockerfile.dev ./client
  - docker build -t wildncrazyguy/multi-nginx  -f nginx/Dockerfile.dev ./nginx
  - docker build -t wildncrazyguy/multi-server -f server/Dockerfile.dev ./server
  - docker build -t wildncrazyguy/multi-worker -f worker/Dockerfile.dev ./worker
  #take images and push up to docker hub
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin  
  - docker push wildncrazyguy/multi-client
  - docker push wildncrazyguy/multi-nginx
  - docker push wildncrazyguy/multi-server
  - docker push wildncrazyguy/multi-worker



#hey travis, put this on aws
#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-west-2-117952388639"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
#  


