version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: server 
    volumes:
      - /app/node_modules
        ./server:/app peterk/complex-react
    environment:
        #setup env variables; if set as k=v, then set at runtime via command line args; if just k, taken from env of host process (good for secrets)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: client 
    volumes:
      - /app/node_modules
        ./client:/app peterk/complex-react-client
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: worker 
    volumes:
      - /app/node_modules
        ./worker:/app peterk/complex-react-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

#  tests:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#      - /app/node_modules
#      - .:/app
#    command: ["npm", "run", "test"]

